// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLGZqX1OCyJnP2Kk5OPc467g2XGJEh8_s',
    appId: '1:317837334806:web:df1b25fbf08b52345b9837',
    messagingSenderId: '317837334806',
    projectId: 'final-project-64a94',
    authDomain: 'final-project-64a94.firebaseapp.com',
    storageBucket: 'final-project-64a94.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbOH2OK3zV_MgFwZ5lhe3pZrkf1BF7upk',
    appId: '1:317837334806:android:77f2e789dde8036a5b9837',
    messagingSenderId: '317837334806',
    projectId: 'final-project-64a94',
    storageBucket: 'final-project-64a94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmWcRO_1hppvhPt4a0k8MPB4a3utpa9i4',
    appId: '1:317837334806:ios:644b78f8270c107e5b9837',
    messagingSenderId: '317837334806',
    projectId: 'final-project-64a94',
    storageBucket: 'final-project-64a94.appspot.com',
    iosClientId: '317837334806-16so9q6t41sfgvej4j76f95q27nf5qtq.apps.googleusercontent.com',
    iosBundleId: 'com.example.fina',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmWcRO_1hppvhPt4a0k8MPB4a3utpa9i4',
    appId: '1:317837334806:ios:644b78f8270c107e5b9837',
    messagingSenderId: '317837334806',
    projectId: 'final-project-64a94',
    storageBucket: 'final-project-64a94.appspot.com',
    iosClientId: '317837334806-16so9q6t41sfgvej4j76f95q27nf5qtq.apps.googleusercontent.com',
    iosBundleId: 'com.example.fina',
  );
}
